<?php

namespace BellonBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{
    public function getConfigByKeyValue($keyValue)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('config')
            ->from('BellonBundle:Config', 'config')
            ->andWhere('config.keyValue = :keyValue')
            ->setParameter('keyValue', $keyValue)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
