<?php

namespace BellonBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getProductByCategorySlug($categorySlug)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('BellonBundle:Product', 'p')
            ->leftJoin('p.productCategory', 'pc')
            ->leftJoin('pc.category', 'c')
            ->andWhere('c.slug = :slug')
            ->setParameter('slug', $categorySlug)
            ->getQuery()
            ->getResult();
    }

    public function getProductByProductCategorySlug($categorySlug)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('p')
            ->from('BellonBundle:Product', 'p')
            ->leftJoin('p.productCategory', 'pc')
            ->andWhere('pc.slug = :slug')
            ->setParameter('slug', $categorySlug)
            ->getQuery()
            ->getResult();
    }
}
