<?php

namespace BellonBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryRepository extends EntityRepository
{
    public function getProductCategoryByCategorySlug($categorySlug)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('pc')
            ->from('BellonBundle:ProductCategory', 'pc')
            ->leftJoin('pc.category', 'c')
            ->andWhere('c.slug = :slug')
            ->setParameter('slug', $categorySlug)
            ->getQuery()
            ->getResult();
    }
}
